### ISSUE TITLE
Mnist loader

### ISSUE THREAD

**Issue by andreaferretti** [jfhg/nimdeep#1]
Hi, I am writing a small neural networks library based on linalg.

The architecture I am using is different from yours, hence it will be difficult to reuse parts of nimdeep, but I would like to include your MNIST format loader (with attribution, of course). Would this be ok for you?

The code is not public yet, but it will be published as Apache2 (I had this license approved at work, and it would be inconvenient to switch to MIT).

**Comment by jfhg** [comment]
Hi Andrea,

On Sat, Jan 21, 2017 at 04:02:32PM -0800, Andrea Ferretti wrote:
> Hi, I am writing a small neural networks library based on linalg.
> 
> The architecture I am using is different from yours, hence it will be difficult to reuse parts of nimdeep, but I would like to include your MNIST format loader (with attribution, of course). Would this be ok for you?

Sure, I'm happy if someone uses it.

> 
> The code is not public yet, but it will be published as Apache2 (I had this license approved at work, and it would be inconvenient to switch to MIT).

For the MNIST loader part that is no problem. I chose the MIT
license for the network.nim part because Michael Nielsons original
code is MIT licensed as well.

Should MNIST loader grow bigger, we could even consider to put
it into a separate nimble package.

  Johannes

**Comment by andreaferretti** [comment]
Thank you, I will let you konw as soon as I have something usable :-)
